
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model Invitation
 * 
 */
export type Invitation = Prisma.InvitationModel
/**
 * Model Property
 * Property represents a real estate asset containing rentable units
 */
export type Property = Prisma.PropertyModel
/**
 * Model Amenity
 * 
 */
export type Amenity = Prisma.AmenityModel
/**
 * Model PropertyAmenity
 * 
 */
export type PropertyAmenity = Prisma.PropertyAmenityModel
/**
 * Model Unit
 * Unit represents a rentable space - listings happen at this level
 */
export type Unit = Prisma.UnitModel
/**
 * Model UnitAmenity
 * 
 */
export type UnitAmenity = Prisma.UnitAmenityModel
/**
 * Model Tenancy
 * Tenancy represents a rental agreement between tenant and unit
 */
export type Tenancy = Prisma.TenancyModel
/**
 * Model Invoice
 * Invoice for tenant billing
 */
export type Invoice = Prisma.InvoiceModel
/**
 * Model Payment
 * Payment records for invoice settlements
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Notification
 * Notification for user alerts
 */
export type Notification = Prisma.NotificationModel
/**
 * Model AuditLog
 * Audit log for important actions
 */
export type AuditLog = Prisma.AuditLogModel
