
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model Invitation
 * 
 */
export type Invitation = Prisma.InvitationModel
/**
 * Model Property
 * Property represents a real estate asset containing rentable units
 */
export type Property = Prisma.PropertyModel
/**
 * Model Amenity
 * 
 */
export type Amenity = Prisma.AmenityModel
/**
 * Model PropertyAmenity
 * 
 */
export type PropertyAmenity = Prisma.PropertyAmenityModel
/**
 * Model Unit
 * Unit represents a rentable space - listings happen at this level
 */
export type Unit = Prisma.UnitModel
/**
 * Model UnitAmenity
 * 
 */
export type UnitAmenity = Prisma.UnitAmenityModel
/**
 * Model Tenancy
 * Tenancy represents a rental agreement between tenant and unit
 */
export type Tenancy = Prisma.TenancyModel
/**
 * Model Invoice
 * Invoice for tenant billing
 */
export type Invoice = Prisma.InvoiceModel
/**
 * Model Payment
 * Payment records for invoice settlements
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Notification
 * Notification for user alerts
 */
export type Notification = Prisma.NotificationModel
/**
 * Model AuditLog
 * Audit log for important actions
 */
export type AuditLog = Prisma.AuditLogModel
