
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PropertyType = {
  APARTMENT: 'APARTMENT',
  HOUSE: 'HOUSE',
  TOWNHOUSE: 'TOWNHOUSE',
  STUDIO: 'STUDIO',
  COMMERCIAL: 'COMMERCIAL',
  BEDSITTER: 'BEDSITTER',
  SINGLE_ROOM: 'SINGLE_ROOM',
  OTHER: 'OTHER'
} as const

export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType]


export const UnitStatus = {
  VACANT: 'VACANT',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
  RESERVED: 'RESERVED'
} as const

export type UnitStatus = (typeof UnitStatus)[keyof typeof UnitStatus]


export const UnitType = {
  APARTMENT: 'APARTMENT',
  HOUSE: 'HOUSE',
  TOWNHOUSE: 'TOWNHOUSE',
  STUDIO: 'STUDIO',
  COMMERCIAL: 'COMMERCIAL',
  BEDSITTER: 'BEDSITTER',
  SINGLE_ROOM: 'SINGLE_ROOM',
  DOUBLE_ROOM: 'DOUBLE_ROOM',
  TRIPLE_ROOM: 'TRIPLE_ROOM',
  QUADRUPLE_ROOM: 'QUADRUPLE_ROOM',
  QUINQUEPLE_ROOM: 'QUINQUEPLE_ROOM',
  SEXTPLE_ROOM: 'SEXTPLE_ROOM',
  SEPTEMBLE_ROOM: 'SEPTEMBLE_ROOM',
  OCTOPLE_ROOM: 'OCTOPLE_ROOM',
  NONUPLE_ROOM: 'NONUPLE_ROOM',
  DECATLE_ROOM: 'DECATLE_ROOM',
  UNDETLE_ROOM: 'UNDETLE_ROOM',
  VIGINTILE_ROOM: 'VIGINTILE_ROOM',
  OTHER: 'OTHER'
} as const

export type UnitType = (typeof UnitType)[keyof typeof UnitType]


export const TenancyStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  RENEWED: 'RENEWED'
} as const

export type TenancyStatus = (typeof TenancyStatus)[keyof typeof TenancyStatus]


export const InvoiceStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
  WRITTEN_OFF: 'WRITTEN_OFF'
} as const

export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus]


export const InvoiceType = {
  RENT: 'RENT',
  DEPOSIT: 'DEPOSIT',
  UTILITY: 'UTILITY',
  PENALTY: 'PENALTY',
  OTHER: 'OTHER'
} as const

export type InvoiceType = (typeof InvoiceType)[keyof typeof InvoiceType]


export const PaymentMethod = {
  MPESA: 'MPESA',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  CARD: 'CARD',
  OTHER: 'OTHER'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const PaymentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]
