-- CreateEnum
CREATE TYPE "UnitType" AS ENUM ('APARTMENT', 'HOUSE', 'TOWNHOUSE', 'STUDIO', 'COMMERCIAL', 'BEDSITTER', 'SINGLE_ROOM', 'DOUBLE_ROOM', 'TRIPLE_ROOM', 'QUADRUPLE_ROOM', 'QUINQUEPLE_ROOM', 'SEXTPLE_ROOM', 'SEPTEMBLE_ROOM', 'OCTOPLE_ROOM', 'NONUPLE_ROOM', 'DECATLE_ROOM', 'UNDETLE_ROOM', 'VIGINTILE_ROOM', 'OTHER');

-- AlterTable
ALTER TABLE "unit" ADD COLUMN     "type" "UnitType" NOT NULL DEFAULT 'APARTMENT';
