
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Property` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Property
 * Property represents a real estate asset containing rentable units
 */
export type PropertyModel = runtime.Types.Result.DefaultSelection<Prisma.$PropertyPayload>

export type AggregateProperty = {
  _count: PropertyCountAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

export type PropertyMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  type: $Enums.PropertyType | null
  address: string | null
  city: string | null
  county: string | null
  postalCode: string | null
  organizationId: string | null
  managerId: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PropertyMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  type: $Enums.PropertyType | null
  address: string | null
  city: string | null
  county: string | null
  postalCode: string | null
  organizationId: string | null
  managerId: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PropertyCountAggregateOutputType = {
  id: number
  name: number
  description: number
  type: number
  address: number
  city: number
  county: number
  postalCode: number
  images: number
  organizationId: number
  managerId: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PropertyMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  type?: true
  address?: true
  city?: true
  county?: true
  postalCode?: true
  organizationId?: true
  managerId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PropertyMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  type?: true
  address?: true
  city?: true
  county?: true
  postalCode?: true
  organizationId?: true
  managerId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PropertyCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  type?: true
  address?: true
  city?: true
  county?: true
  postalCode?: true
  images?: true
  organizationId?: true
  managerId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PropertyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Property to aggregate.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Properties
  **/
  _count?: true | PropertyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PropertyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PropertyMaxAggregateInputType
}

export type GetPropertyAggregateType<T extends PropertyAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty[P]>
}




export type PropertyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithAggregationInput | Prisma.PropertyOrderByWithAggregationInput[]
  by: Prisma.PropertyScalarFieldEnum[] | Prisma.PropertyScalarFieldEnum
  having?: Prisma.PropertyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PropertyCountAggregateInputType | true
  _min?: PropertyMinAggregateInputType
  _max?: PropertyMaxAggregateInputType
}

export type PropertyGroupByOutputType = {
  id: string
  name: string
  description: string | null
  type: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode: string | null
  images: string[]
  organizationId: string
  managerId: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PropertyCountAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

type GetPropertyGroupByPayload<T extends PropertyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PropertyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PropertyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
      }
    >
  >



export type PropertyWhereInput = {
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  id?: Prisma.StringFilter<"Property"> | string
  name?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  address?: Prisma.StringFilter<"Property"> | string
  city?: Prisma.StringFilter<"Property"> | string
  county?: Prisma.StringFilter<"Property"> | string
  postalCode?: Prisma.StringNullableFilter<"Property"> | string | null
  images?: Prisma.StringNullableListFilter<"Property">
  organizationId?: Prisma.StringFilter<"Property"> | string
  managerId?: Prisma.StringNullableFilter<"Property"> | string | null
  isActive?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  manager?: Prisma.XOR<Prisma.MemberNullableScalarRelationFilter, Prisma.MemberWhereInput> | null
  units?: Prisma.UnitListRelationFilter
  amenities?: Prisma.PropertyAmenityListRelationFilter
}

export type PropertyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  county?: Prisma.SortOrder
  postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  managerId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  manager?: Prisma.MemberOrderByWithRelationInput
  units?: Prisma.UnitOrderByRelationAggregateInput
  amenities?: Prisma.PropertyAmenityOrderByRelationAggregateInput
}

export type PropertyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  name?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  address?: Prisma.StringFilter<"Property"> | string
  city?: Prisma.StringFilter<"Property"> | string
  county?: Prisma.StringFilter<"Property"> | string
  postalCode?: Prisma.StringNullableFilter<"Property"> | string | null
  images?: Prisma.StringNullableListFilter<"Property">
  organizationId?: Prisma.StringFilter<"Property"> | string
  managerId?: Prisma.StringNullableFilter<"Property"> | string | null
  isActive?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  manager?: Prisma.XOR<Prisma.MemberNullableScalarRelationFilter, Prisma.MemberWhereInput> | null
  units?: Prisma.UnitListRelationFilter
  amenities?: Prisma.PropertyAmenityListRelationFilter
}, "id">

export type PropertyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  county?: Prisma.SortOrder
  postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  managerId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PropertyCountOrderByAggregateInput
  _max?: Prisma.PropertyMaxOrderByAggregateInput
  _min?: Prisma.PropertyMinOrderByAggregateInput
}

export type PropertyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PropertyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Property"> | string
  name?: Prisma.StringWithAggregatesFilter<"Property"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Property"> | string | null
  type?: Prisma.EnumPropertyTypeWithAggregatesFilter<"Property"> | $Enums.PropertyType
  address?: Prisma.StringWithAggregatesFilter<"Property"> | string
  city?: Prisma.StringWithAggregatesFilter<"Property"> | string
  county?: Prisma.StringWithAggregatesFilter<"Property"> | string
  postalCode?: Prisma.StringNullableWithAggregatesFilter<"Property"> | string | null
  images?: Prisma.StringNullableListFilter<"Property">
  organizationId?: Prisma.StringWithAggregatesFilter<"Property"> | string
  managerId?: Prisma.StringNullableWithAggregatesFilter<"Property"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
}

export type PropertyCreateInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutPropertiesInput
  manager?: Prisma.MemberCreateNestedOneWithoutManagedPropertiesInput
  units?: Prisma.UnitCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  units?: Prisma.UnitUncheckedCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutPropertiesNestedInput
  manager?: Prisma.MemberUpdateOneWithoutManagedPropertiesNestedInput
  units?: Prisma.UnitUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  units?: Prisma.UnitUncheckedUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PropertyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyListRelationFilter = {
  every?: Prisma.PropertyWhereInput
  some?: Prisma.PropertyWhereInput
  none?: Prisma.PropertyWhereInput
}

export type PropertyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type PropertyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  county?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  images?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PropertyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  county?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PropertyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  county?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PropertyScalarRelationFilter = {
  is?: Prisma.PropertyWhereInput
  isNot?: Prisma.PropertyWhereInput
}

export type PropertyCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput> | Prisma.PropertyCreateWithoutOrganizationInput[] | Prisma.PropertyUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOrganizationInput | Prisma.PropertyCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.PropertyCreateManyOrganizationInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput> | Prisma.PropertyCreateWithoutOrganizationInput[] | Prisma.PropertyUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOrganizationInput | Prisma.PropertyCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.PropertyCreateManyOrganizationInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput> | Prisma.PropertyCreateWithoutOrganizationInput[] | Prisma.PropertyUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOrganizationInput | Prisma.PropertyCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.PropertyUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.PropertyCreateManyOrganizationInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.PropertyUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutOrganizationInput | Prisma.PropertyUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput> | Prisma.PropertyCreateWithoutOrganizationInput[] | Prisma.PropertyUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOrganizationInput | Prisma.PropertyCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.PropertyUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.PropertyCreateManyOrganizationInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.PropertyUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutOrganizationInput | Prisma.PropertyUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput> | Prisma.PropertyCreateWithoutManagerInput[] | Prisma.PropertyUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutManagerInput | Prisma.PropertyCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.PropertyCreateManyManagerInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUncheckedCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput> | Prisma.PropertyCreateWithoutManagerInput[] | Prisma.PropertyUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutManagerInput | Prisma.PropertyCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.PropertyCreateManyManagerInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput> | Prisma.PropertyCreateWithoutManagerInput[] | Prisma.PropertyUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutManagerInput | Prisma.PropertyCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutManagerInput | Prisma.PropertyUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.PropertyCreateManyManagerInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutManagerInput | Prisma.PropertyUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutManagerInput | Prisma.PropertyUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyUncheckedUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput> | Prisma.PropertyCreateWithoutManagerInput[] | Prisma.PropertyUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutManagerInput | Prisma.PropertyCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutManagerInput | Prisma.PropertyUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.PropertyCreateManyManagerInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutManagerInput | Prisma.PropertyUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutManagerInput | Prisma.PropertyUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyCreateimagesInput = {
  set: string[]
}

export type EnumPropertyTypeFieldUpdateOperationsInput = {
  set?: $Enums.PropertyType
}

export type PropertyUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type PropertyCreateNestedOneWithoutAmenitiesInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAmenitiesInput, Prisma.PropertyUncheckedCreateWithoutAmenitiesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAmenitiesInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutAmenitiesNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutAmenitiesInput, Prisma.PropertyUncheckedCreateWithoutAmenitiesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutAmenitiesInput
  upsert?: Prisma.PropertyUpsertWithoutAmenitiesInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutAmenitiesInput, Prisma.PropertyUpdateWithoutAmenitiesInput>, Prisma.PropertyUncheckedUpdateWithoutAmenitiesInput>
}

export type PropertyCreateNestedOneWithoutUnitsInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutUnitsInput, Prisma.PropertyUncheckedCreateWithoutUnitsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutUnitsInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutUnitsNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutUnitsInput, Prisma.PropertyUncheckedCreateWithoutUnitsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutUnitsInput
  upsert?: Prisma.PropertyUpsertWithoutUnitsInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutUnitsInput, Prisma.PropertyUpdateWithoutUnitsInput>, Prisma.PropertyUncheckedUpdateWithoutUnitsInput>
}

export type PropertyCreateWithoutOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  manager?: Prisma.MemberCreateNestedOneWithoutManagedPropertiesInput
  units?: Prisma.UnitCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  units?: Prisma.UnitUncheckedCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput>
}

export type PropertyCreateManyOrganizationInputEnvelope = {
  data: Prisma.PropertyCreateManyOrganizationInput | Prisma.PropertyCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type PropertyUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.PropertyWhereUniqueInput
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutOrganizationInput, Prisma.PropertyUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutOrganizationInput, Prisma.PropertyUncheckedCreateWithoutOrganizationInput>
}

export type PropertyUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.PropertyWhereUniqueInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutOrganizationInput, Prisma.PropertyUncheckedUpdateWithoutOrganizationInput>
}

export type PropertyUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.PropertyScalarWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyWithoutOrganizationInput>
}

export type PropertyScalarWhereInput = {
  AND?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
  OR?: Prisma.PropertyScalarWhereInput[]
  NOT?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
  id?: Prisma.StringFilter<"Property"> | string
  name?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  address?: Prisma.StringFilter<"Property"> | string
  city?: Prisma.StringFilter<"Property"> | string
  county?: Prisma.StringFilter<"Property"> | string
  postalCode?: Prisma.StringNullableFilter<"Property"> | string | null
  images?: Prisma.StringNullableListFilter<"Property">
  organizationId?: Prisma.StringFilter<"Property"> | string
  managerId?: Prisma.StringNullableFilter<"Property"> | string | null
  isActive?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
}

export type PropertyCreateWithoutManagerInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutPropertiesInput
  units?: Prisma.UnitCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutManagerInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  units?: Prisma.UnitUncheckedCreateNestedManyWithoutPropertyInput
  amenities?: Prisma.PropertyAmenityUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutManagerInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput>
}

export type PropertyCreateManyManagerInputEnvelope = {
  data: Prisma.PropertyCreateManyManagerInput | Prisma.PropertyCreateManyManagerInput[]
  skipDuplicates?: boolean
}

export type PropertyUpsertWithWhereUniqueWithoutManagerInput = {
  where: Prisma.PropertyWhereUniqueInput
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutManagerInput, Prisma.PropertyUncheckedUpdateWithoutManagerInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutManagerInput, Prisma.PropertyUncheckedCreateWithoutManagerInput>
}

export type PropertyUpdateWithWhereUniqueWithoutManagerInput = {
  where: Prisma.PropertyWhereUniqueInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutManagerInput, Prisma.PropertyUncheckedUpdateWithoutManagerInput>
}

export type PropertyUpdateManyWithWhereWithoutManagerInput = {
  where: Prisma.PropertyScalarWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyWithoutManagerInput>
}

export type PropertyCreateWithoutAmenitiesInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutPropertiesInput
  manager?: Prisma.MemberCreateNestedOneWithoutManagedPropertiesInput
  units?: Prisma.UnitCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutAmenitiesInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  units?: Prisma.UnitUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutAmenitiesInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAmenitiesInput, Prisma.PropertyUncheckedCreateWithoutAmenitiesInput>
}

export type PropertyUpsertWithoutAmenitiesInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutAmenitiesInput, Prisma.PropertyUncheckedUpdateWithoutAmenitiesInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutAmenitiesInput, Prisma.PropertyUncheckedCreateWithoutAmenitiesInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutAmenitiesInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutAmenitiesInput, Prisma.PropertyUncheckedUpdateWithoutAmenitiesInput>
}

export type PropertyUpdateWithoutAmenitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutPropertiesNestedInput
  manager?: Prisma.MemberUpdateOneWithoutManagedPropertiesNestedInput
  units?: Prisma.UnitUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutAmenitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  units?: Prisma.UnitUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutUnitsInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutPropertiesInput
  manager?: Prisma.MemberCreateNestedOneWithoutManagedPropertiesInput
  amenities?: Prisma.PropertyAmenityCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutUnitsInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  amenities?: Prisma.PropertyAmenityUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutUnitsInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutUnitsInput, Prisma.PropertyUncheckedCreateWithoutUnitsInput>
}

export type PropertyUpsertWithoutUnitsInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutUnitsInput, Prisma.PropertyUncheckedUpdateWithoutUnitsInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutUnitsInput, Prisma.PropertyUncheckedCreateWithoutUnitsInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutUnitsInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutUnitsInput, Prisma.PropertyUncheckedUpdateWithoutUnitsInput>
}

export type PropertyUpdateWithoutUnitsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutPropertiesNestedInput
  manager?: Prisma.MemberUpdateOneWithoutManagedPropertiesNestedInput
  amenities?: Prisma.PropertyAmenityUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutUnitsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amenities?: Prisma.PropertyAmenityUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  managerId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PropertyUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  manager?: Prisma.MemberUpdateOneWithoutManagedPropertiesNestedInput
  units?: Prisma.UnitUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  units?: Prisma.UnitUncheckedUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  managerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyCreateManyManagerInput = {
  id?: string
  name: string
  description?: string | null
  type?: $Enums.PropertyType
  address: string
  city: string
  county: string
  postalCode?: string | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  organizationId: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PropertyUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutPropertiesNestedInput
  units?: Prisma.UnitUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  units?: Prisma.UnitUncheckedUpdateManyWithoutPropertyNestedInput
  amenities?: Prisma.PropertyAmenityUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateManyWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PropertyCountOutputType
 */

export type PropertyCountOutputType = {
  units: number
  amenities: number
}

export type PropertyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  units?: boolean | PropertyCountOutputTypeCountUnitsArgs
  amenities?: boolean | PropertyCountOutputTypeCountAmenitiesArgs
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyCountOutputType
   */
  select?: Prisma.PropertyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountUnitsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountAmenitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyAmenityWhereInput
}


export type PropertySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  address?: boolean
  city?: boolean
  county?: boolean
  postalCode?: boolean
  images?: boolean
  organizationId?: boolean
  managerId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
  units?: boolean | Prisma.Property$unitsArgs<ExtArgs>
  amenities?: boolean | Prisma.Property$amenitiesArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  address?: boolean
  city?: boolean
  county?: boolean
  postalCode?: boolean
  images?: boolean
  organizationId?: boolean
  managerId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  address?: boolean
  city?: boolean
  county?: boolean
  postalCode?: boolean
  images?: boolean
  organizationId?: boolean
  managerId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  address?: boolean
  city?: boolean
  county?: boolean
  postalCode?: boolean
  images?: boolean
  organizationId?: boolean
  managerId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PropertyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "type" | "address" | "city" | "county" | "postalCode" | "images" | "organizationId" | "managerId" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["property"]>
export type PropertyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
  units?: boolean | Prisma.Property$unitsArgs<ExtArgs>
  amenities?: boolean | Prisma.Property$amenitiesArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}
export type PropertyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
}
export type PropertyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  manager?: boolean | Prisma.Property$managerArgs<ExtArgs>
}

export type $PropertyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Property"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    manager: Prisma.$MemberPayload<ExtArgs> | null
    units: Prisma.$UnitPayload<ExtArgs>[]
    amenities: Prisma.$PropertyAmenityPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    type: $Enums.PropertyType
    address: string
    city: string
    county: string
    postalCode: string | null
    images: string[]
    organizationId: string
    managerId: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["property"]>
  composites: {}
}

export type PropertyGetPayload<S extends boolean | null | undefined | PropertyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PropertyPayload, S>

export type PropertyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PropertyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PropertyCountAggregateInputType | true
  }

export interface PropertyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Property'], meta: { name: 'Property' } }
  /**
   * Find zero or one Property that matches the filter.
   * @param {PropertyFindUniqueArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PropertyFindUniqueArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PropertyFindUniqueOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PropertyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PropertyFindFirstArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PropertyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Properties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Properties
   * const properties = await prisma.property.findMany()
   * 
   * // Get first 10 Properties
   * const properties = await prisma.property.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const propertyWithIdOnly = await prisma.property.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PropertyFindManyArgs>(args?: Prisma.SelectSubset<T, PropertyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property.
   * @param {PropertyCreateArgs} args - Arguments to create a Property.
   * @example
   * // Create one Property
   * const Property = await prisma.property.create({
   *   data: {
   *     // ... data to create a Property
   *   }
   * })
   * 
   */
  create<T extends PropertyCreateArgs>(args: Prisma.SelectSubset<T, PropertyCreateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Properties.
   * @param {PropertyCreateManyArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PropertyCreateManyArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Properties and returns the data saved in the database.
   * @param {PropertyCreateManyAndReturnArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PropertyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Property.
   * @param {PropertyDeleteArgs} args - Arguments to delete one Property.
   * @example
   * // Delete one Property
   * const Property = await prisma.property.delete({
   *   where: {
   *     // ... filter to delete one Property
   *   }
   * })
   * 
   */
  delete<T extends PropertyDeleteArgs>(args: Prisma.SelectSubset<T, PropertyDeleteArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property.
   * @param {PropertyUpdateArgs} args - Arguments to update one Property.
   * @example
   * // Update one Property
   * const property = await prisma.property.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PropertyUpdateArgs>(args: Prisma.SelectSubset<T, PropertyUpdateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Properties.
   * @param {PropertyDeleteManyArgs} args - Arguments to filter Properties to delete.
   * @example
   * // Delete a few Properties
   * const { count } = await prisma.property.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PropertyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PropertyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PropertyUpdateManyArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties and returns the data updated in the database.
   * @param {PropertyUpdateManyAndReturnArgs} args - Arguments to update many Properties.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PropertyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Property.
   * @param {PropertyUpsertArgs} args - Arguments to update or create a Property.
   * @example
   * // Update or create a Property
   * const property = await prisma.property.upsert({
   *   create: {
   *     // ... data to create a Property
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property we want to update
   *   }
   * })
   */
  upsert<T extends PropertyUpsertArgs>(args: Prisma.SelectSubset<T, PropertyUpsertArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyCountArgs} args - Arguments to filter Properties to count.
   * @example
   * // Count the number of Properties
   * const count = await prisma.property.count({
   *   where: {
   *     // ... the filter for the Properties we want to count
   *   }
   * })
  **/
  count<T extends PropertyCountArgs>(
    args?: Prisma.Subset<T, PropertyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PropertyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PropertyAggregateArgs>(args: Prisma.Subset<T, PropertyAggregateArgs>): Prisma.PrismaPromise<GetPropertyAggregateType<T>>

  /**
   * Group by Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PropertyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PropertyGroupByArgs['orderBy'] }
      : { orderBy?: PropertyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PropertyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPropertyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Property model
 */
readonly fields: PropertyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Property.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PropertyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  manager<T extends Prisma.Property$managerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$managerArgs<ExtArgs>>): Prisma.Prisma__MemberClient<runtime.Types.Result.GetResult<Prisma.$MemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  units<T extends Prisma.Property$unitsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$unitsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  amenities<T extends Prisma.Property$amenitiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$amenitiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyAmenityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Property model
 */
export interface PropertyFieldRefs {
  readonly id: Prisma.FieldRef<"Property", 'String'>
  readonly name: Prisma.FieldRef<"Property", 'String'>
  readonly description: Prisma.FieldRef<"Property", 'String'>
  readonly type: Prisma.FieldRef<"Property", 'PropertyType'>
  readonly address: Prisma.FieldRef<"Property", 'String'>
  readonly city: Prisma.FieldRef<"Property", 'String'>
  readonly county: Prisma.FieldRef<"Property", 'String'>
  readonly postalCode: Prisma.FieldRef<"Property", 'String'>
  readonly images: Prisma.FieldRef<"Property", 'String[]'>
  readonly organizationId: Prisma.FieldRef<"Property", 'String'>
  readonly managerId: Prisma.FieldRef<"Property", 'String'>
  readonly isActive: Prisma.FieldRef<"Property", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Property", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Property", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Property findUnique
 */
export type PropertyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findUniqueOrThrow
 */
export type PropertyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findFirst
 */
export type PropertyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findFirstOrThrow
 */
export type PropertyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findMany
 */
export type PropertyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Properties to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property create
 */
export type PropertyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to create a Property.
   */
  data: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
}

/**
 * Property createMany
 */
export type PropertyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Property createManyAndReturn
 */
export type PropertyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Property update
 */
export type PropertyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to update a Property.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
  /**
   * Choose, which Property to update.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property updateMany
 */
export type PropertyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
}

/**
 * Property updateManyAndReturn
 */
export type PropertyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Property upsert
 */
export type PropertyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The filter to search for the Property to update in case it exists.
   */
  where: Prisma.PropertyWhereUniqueInput
  /**
   * In case the Property found by the `where` argument doesn't exist, create a new Property with this data.
   */
  create: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
  /**
   * In case the Property was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
}

/**
 * Property delete
 */
export type PropertyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter which Property to delete.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property deleteMany
 */
export type PropertyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Properties to delete
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to delete.
   */
  limit?: number
}

/**
 * Property.manager
 */
export type Property$managerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Member
   */
  select?: Prisma.MemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Member
   */
  omit?: Prisma.MemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberInclude<ExtArgs> | null
  where?: Prisma.MemberWhereInput
}

/**
 * Property.units
 */
export type Property$unitsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  where?: Prisma.UnitWhereInput
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  cursor?: Prisma.UnitWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Property.amenities
 */
export type Property$amenitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyAmenity
   */
  select?: Prisma.PropertyAmenitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PropertyAmenity
   */
  omit?: Prisma.PropertyAmenityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyAmenityInclude<ExtArgs> | null
  where?: Prisma.PropertyAmenityWhereInput
  orderBy?: Prisma.PropertyAmenityOrderByWithRelationInput | Prisma.PropertyAmenityOrderByWithRelationInput[]
  cursor?: Prisma.PropertyAmenityWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PropertyAmenityScalarFieldEnum | Prisma.PropertyAmenityScalarFieldEnum[]
}

/**
 * Property without action
 */
export type PropertyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
}
