
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Unit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Unit
 * Unit represents a rentable space - listings happen at this level
 */
export type UnitModel = runtime.Types.Result.DefaultSelection<Prisma.$UnitPayload>

export type AggregateUnit = {
  _count: UnitCountAggregateOutputType | null
  _avg: UnitAvgAggregateOutputType | null
  _sum: UnitSumAggregateOutputType | null
  _min: UnitMinAggregateOutputType | null
  _max: UnitMaxAggregateOutputType | null
}

export type UnitAvgAggregateOutputType = {
  rentAmount: runtime.Decimal | null
  depositAmount: runtime.Decimal | null
  bedrooms: number | null
  bathrooms: number | null
  squareMeters: number | null
}

export type UnitSumAggregateOutputType = {
  rentAmount: runtime.Decimal | null
  depositAmount: runtime.Decimal | null
  bedrooms: number | null
  bathrooms: number | null
  squareMeters: number | null
}

export type UnitMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  locationInProperty: string | null
  rentAmount: runtime.Decimal | null
  depositAmount: runtime.Decimal | null
  bedrooms: number | null
  bathrooms: number | null
  squareMeters: number | null
  status: $Enums.UnitStatus | null
  isListed: boolean | null
  listingTitle: string | null
  listingDescription: string | null
  listedAt: Date | null
  propertyId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnitMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  locationInProperty: string | null
  rentAmount: runtime.Decimal | null
  depositAmount: runtime.Decimal | null
  bedrooms: number | null
  bathrooms: number | null
  squareMeters: number | null
  status: $Enums.UnitStatus | null
  isListed: boolean | null
  listingTitle: string | null
  listingDescription: string | null
  listedAt: Date | null
  propertyId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnitCountAggregateOutputType = {
  id: number
  title: number
  description: number
  locationInProperty: number
  rentAmount: number
  depositAmount: number
  bedrooms: number
  bathrooms: number
  squareMeters: number
  images: number
  status: number
  isListed: number
  listingTitle: number
  listingDescription: number
  listedAt: number
  propertyId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UnitAvgAggregateInputType = {
  rentAmount?: true
  depositAmount?: true
  bedrooms?: true
  bathrooms?: true
  squareMeters?: true
}

export type UnitSumAggregateInputType = {
  rentAmount?: true
  depositAmount?: true
  bedrooms?: true
  bathrooms?: true
  squareMeters?: true
}

export type UnitMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  locationInProperty?: true
  rentAmount?: true
  depositAmount?: true
  bedrooms?: true
  bathrooms?: true
  squareMeters?: true
  status?: true
  isListed?: true
  listingTitle?: true
  listingDescription?: true
  listedAt?: true
  propertyId?: true
  createdAt?: true
  updatedAt?: true
}

export type UnitMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  locationInProperty?: true
  rentAmount?: true
  depositAmount?: true
  bedrooms?: true
  bathrooms?: true
  squareMeters?: true
  status?: true
  isListed?: true
  listingTitle?: true
  listingDescription?: true
  listedAt?: true
  propertyId?: true
  createdAt?: true
  updatedAt?: true
}

export type UnitCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  locationInProperty?: true
  rentAmount?: true
  depositAmount?: true
  bedrooms?: true
  bathrooms?: true
  squareMeters?: true
  images?: true
  status?: true
  isListed?: true
  listingTitle?: true
  listingDescription?: true
  listedAt?: true
  propertyId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UnitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Unit to aggregate.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Units
  **/
  _count?: true | UnitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UnitAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UnitSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnitMaxAggregateInputType
}

export type GetUnitAggregateType<T extends UnitAggregateArgs> = {
      [P in keyof T & keyof AggregateUnit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnit[P]>
    : Prisma.GetScalarType<T[P], AggregateUnit[P]>
}




export type UnitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitWhereInput
  orderBy?: Prisma.UnitOrderByWithAggregationInput | Prisma.UnitOrderByWithAggregationInput[]
  by: Prisma.UnitScalarFieldEnum[] | Prisma.UnitScalarFieldEnum
  having?: Prisma.UnitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnitCountAggregateInputType | true
  _avg?: UnitAvgAggregateInputType
  _sum?: UnitSumAggregateInputType
  _min?: UnitMinAggregateInputType
  _max?: UnitMaxAggregateInputType
}

export type UnitGroupByOutputType = {
  id: string
  title: string
  description: string | null
  locationInProperty: string | null
  rentAmount: runtime.Decimal
  depositAmount: runtime.Decimal | null
  bedrooms: number
  bathrooms: number
  squareMeters: number | null
  images: string[]
  status: $Enums.UnitStatus
  isListed: boolean
  listingTitle: string | null
  listingDescription: string | null
  listedAt: Date | null
  propertyId: string
  createdAt: Date
  updatedAt: Date
  _count: UnitCountAggregateOutputType | null
  _avg: UnitAvgAggregateOutputType | null
  _sum: UnitSumAggregateOutputType | null
  _min: UnitMinAggregateOutputType | null
  _max: UnitMaxAggregateOutputType | null
}

type GetUnitGroupByPayload<T extends UnitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnitGroupByOutputType[P]>
      }
    >
  >



export type UnitWhereInput = {
  AND?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  OR?: Prisma.UnitWhereInput[]
  NOT?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  id?: Prisma.StringFilter<"Unit"> | string
  title?: Prisma.StringFilter<"Unit"> | string
  description?: Prisma.StringNullableFilter<"Unit"> | string | null
  locationInProperty?: Prisma.StringNullableFilter<"Unit"> | string | null
  rentAmount?: Prisma.DecimalFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.DecimalNullableFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFilter<"Unit"> | number
  bathrooms?: Prisma.IntFilter<"Unit"> | number
  squareMeters?: Prisma.FloatNullableFilter<"Unit"> | number | null
  images?: Prisma.StringNullableListFilter<"Unit">
  status?: Prisma.EnumUnitStatusFilter<"Unit"> | $Enums.UnitStatus
  isListed?: Prisma.BoolFilter<"Unit"> | boolean
  listingTitle?: Prisma.StringNullableFilter<"Unit"> | string | null
  listingDescription?: Prisma.StringNullableFilter<"Unit"> | string | null
  listedAt?: Prisma.DateTimeNullableFilter<"Unit"> | Date | string | null
  propertyId?: Prisma.StringFilter<"Unit"> | string
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  tenancies?: Prisma.TenancyListRelationFilter
  amenities?: Prisma.UnitAmenityListRelationFilter
}

export type UnitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  locationInProperty?: Prisma.SortOrderInput | Prisma.SortOrder
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isListed?: Prisma.SortOrder
  listingTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  listingDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  listedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  property?: Prisma.PropertyOrderByWithRelationInput
  tenancies?: Prisma.TenancyOrderByRelationAggregateInput
  amenities?: Prisma.UnitAmenityOrderByRelationAggregateInput
}

export type UnitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  OR?: Prisma.UnitWhereInput[]
  NOT?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  title?: Prisma.StringFilter<"Unit"> | string
  description?: Prisma.StringNullableFilter<"Unit"> | string | null
  locationInProperty?: Prisma.StringNullableFilter<"Unit"> | string | null
  rentAmount?: Prisma.DecimalFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.DecimalNullableFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFilter<"Unit"> | number
  bathrooms?: Prisma.IntFilter<"Unit"> | number
  squareMeters?: Prisma.FloatNullableFilter<"Unit"> | number | null
  images?: Prisma.StringNullableListFilter<"Unit">
  status?: Prisma.EnumUnitStatusFilter<"Unit"> | $Enums.UnitStatus
  isListed?: Prisma.BoolFilter<"Unit"> | boolean
  listingTitle?: Prisma.StringNullableFilter<"Unit"> | string | null
  listingDescription?: Prisma.StringNullableFilter<"Unit"> | string | null
  listedAt?: Prisma.DateTimeNullableFilter<"Unit"> | Date | string | null
  propertyId?: Prisma.StringFilter<"Unit"> | string
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  tenancies?: Prisma.TenancyListRelationFilter
  amenities?: Prisma.UnitAmenityListRelationFilter
}, "id">

export type UnitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  locationInProperty?: Prisma.SortOrderInput | Prisma.SortOrder
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isListed?: Prisma.SortOrder
  listingTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  listingDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  listedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UnitCountOrderByAggregateInput
  _avg?: Prisma.UnitAvgOrderByAggregateInput
  _max?: Prisma.UnitMaxOrderByAggregateInput
  _min?: Prisma.UnitMinOrderByAggregateInput
  _sum?: Prisma.UnitSumOrderByAggregateInput
}

export type UnitScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnitScalarWhereWithAggregatesInput | Prisma.UnitScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnitScalarWhereWithAggregatesInput | Prisma.UnitScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  title?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  locationInProperty?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  rentAmount?: Prisma.DecimalWithAggregatesFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.DecimalNullableWithAggregatesFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntWithAggregatesFilter<"Unit"> | number
  bathrooms?: Prisma.IntWithAggregatesFilter<"Unit"> | number
  squareMeters?: Prisma.FloatNullableWithAggregatesFilter<"Unit"> | number | null
  images?: Prisma.StringNullableListFilter<"Unit">
  status?: Prisma.EnumUnitStatusWithAggregatesFilter<"Unit"> | $Enums.UnitStatus
  isListed?: Prisma.BoolWithAggregatesFilter<"Unit"> | boolean
  listingTitle?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  listingDescription?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  listedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Unit"> | Date | string | null
  propertyId?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Unit"> | Date | string
}

export type UnitCreateInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutUnitsInput
  tenancies?: Prisma.TenancyCreateNestedManyWithoutUnitInput
  amenities?: Prisma.UnitAmenityCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  propertyId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  tenancies?: Prisma.TenancyUncheckedCreateNestedManyWithoutUnitInput
  amenities?: Prisma.UnitAmenityUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutUnitsNestedInput
  tenancies?: Prisma.TenancyUpdateManyWithoutUnitNestedInput
  amenities?: Prisma.UnitAmenityUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenancies?: Prisma.TenancyUncheckedUpdateManyWithoutUnitNestedInput
  amenities?: Prisma.UnitAmenityUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  propertyId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitListRelationFilter = {
  every?: Prisma.UnitWhereInput
  some?: Prisma.UnitWhereInput
  none?: Prisma.UnitWhereInput
}

export type UnitOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  locationInProperty?: Prisma.SortOrder
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isListed?: Prisma.SortOrder
  listingTitle?: Prisma.SortOrder
  listingDescription?: Prisma.SortOrder
  listedAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitAvgOrderByAggregateInput = {
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrder
}

export type UnitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  locationInProperty?: Prisma.SortOrder
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isListed?: Prisma.SortOrder
  listingTitle?: Prisma.SortOrder
  listingDescription?: Prisma.SortOrder
  listedAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  locationInProperty?: Prisma.SortOrder
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isListed?: Prisma.SortOrder
  listingTitle?: Prisma.SortOrder
  listingDescription?: Prisma.SortOrder
  listedAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitSumOrderByAggregateInput = {
  rentAmount?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  squareMeters?: Prisma.SortOrder
}

export type UnitScalarRelationFilter = {
  is?: Prisma.UnitWhereInput
  isNot?: Prisma.UnitWhereInput
}

export type UnitCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput> | Prisma.UnitCreateWithoutPropertyInput[] | Prisma.UnitUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPropertyInput | Prisma.UnitCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.UnitCreateManyPropertyInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput> | Prisma.UnitCreateWithoutPropertyInput[] | Prisma.UnitUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPropertyInput | Prisma.UnitCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.UnitCreateManyPropertyInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput> | Prisma.UnitCreateWithoutPropertyInput[] | Prisma.UnitUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPropertyInput | Prisma.UnitCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutPropertyInput | Prisma.UnitUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.UnitCreateManyPropertyInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutPropertyInput | Prisma.UnitUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutPropertyInput | Prisma.UnitUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput> | Prisma.UnitCreateWithoutPropertyInput[] | Prisma.UnitUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPropertyInput | Prisma.UnitCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutPropertyInput | Prisma.UnitUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.UnitCreateManyPropertyInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutPropertyInput | Prisma.UnitUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutPropertyInput | Prisma.UnitUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitCreateimagesInput = {
  set: string[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UnitUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type EnumUnitStatusFieldUpdateOperationsInput = {
  set?: $Enums.UnitStatus
}

export type UnitCreateNestedOneWithoutAmenitiesInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutAmenitiesInput, Prisma.UnitUncheckedCreateWithoutAmenitiesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutAmenitiesInput
  connect?: Prisma.UnitWhereUniqueInput
}

export type UnitUpdateOneRequiredWithoutAmenitiesNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutAmenitiesInput, Prisma.UnitUncheckedCreateWithoutAmenitiesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutAmenitiesInput
  upsert?: Prisma.UnitUpsertWithoutAmenitiesInput
  connect?: Prisma.UnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnitUpdateToOneWithWhereWithoutAmenitiesInput, Prisma.UnitUpdateWithoutAmenitiesInput>, Prisma.UnitUncheckedUpdateWithoutAmenitiesInput>
}

export type UnitCreateNestedOneWithoutTenanciesInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutTenanciesInput, Prisma.UnitUncheckedCreateWithoutTenanciesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutTenanciesInput
  connect?: Prisma.UnitWhereUniqueInput
}

export type UnitUpdateOneRequiredWithoutTenanciesNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutTenanciesInput, Prisma.UnitUncheckedCreateWithoutTenanciesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutTenanciesInput
  upsert?: Prisma.UnitUpsertWithoutTenanciesInput
  connect?: Prisma.UnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnitUpdateToOneWithWhereWithoutTenanciesInput, Prisma.UnitUpdateWithoutTenanciesInput>, Prisma.UnitUncheckedUpdateWithoutTenanciesInput>
}

export type UnitCreateWithoutPropertyInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tenancies?: Prisma.TenancyCreateNestedManyWithoutUnitInput
  amenities?: Prisma.UnitAmenityCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutPropertyInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tenancies?: Prisma.TenancyUncheckedCreateNestedManyWithoutUnitInput
  amenities?: Prisma.UnitAmenityUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutPropertyInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput>
}

export type UnitCreateManyPropertyInputEnvelope = {
  data: Prisma.UnitCreateManyPropertyInput | Prisma.UnitCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type UnitUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.UnitWhereUniqueInput
  update: Prisma.XOR<Prisma.UnitUpdateWithoutPropertyInput, Prisma.UnitUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutPropertyInput, Prisma.UnitUncheckedCreateWithoutPropertyInput>
}

export type UnitUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.UnitWhereUniqueInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutPropertyInput, Prisma.UnitUncheckedUpdateWithoutPropertyInput>
}

export type UnitUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.UnitScalarWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyWithoutPropertyInput>
}

export type UnitScalarWhereInput = {
  AND?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
  OR?: Prisma.UnitScalarWhereInput[]
  NOT?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
  id?: Prisma.StringFilter<"Unit"> | string
  title?: Prisma.StringFilter<"Unit"> | string
  description?: Prisma.StringNullableFilter<"Unit"> | string | null
  locationInProperty?: Prisma.StringNullableFilter<"Unit"> | string | null
  rentAmount?: Prisma.DecimalFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.DecimalNullableFilter<"Unit"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFilter<"Unit"> | number
  bathrooms?: Prisma.IntFilter<"Unit"> | number
  squareMeters?: Prisma.FloatNullableFilter<"Unit"> | number | null
  images?: Prisma.StringNullableListFilter<"Unit">
  status?: Prisma.EnumUnitStatusFilter<"Unit"> | $Enums.UnitStatus
  isListed?: Prisma.BoolFilter<"Unit"> | boolean
  listingTitle?: Prisma.StringNullableFilter<"Unit"> | string | null
  listingDescription?: Prisma.StringNullableFilter<"Unit"> | string | null
  listedAt?: Prisma.DateTimeNullableFilter<"Unit"> | Date | string | null
  propertyId?: Prisma.StringFilter<"Unit"> | string
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
}

export type UnitCreateWithoutAmenitiesInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutUnitsInput
  tenancies?: Prisma.TenancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutAmenitiesInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  propertyId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  tenancies?: Prisma.TenancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutAmenitiesInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutAmenitiesInput, Prisma.UnitUncheckedCreateWithoutAmenitiesInput>
}

export type UnitUpsertWithoutAmenitiesInput = {
  update: Prisma.XOR<Prisma.UnitUpdateWithoutAmenitiesInput, Prisma.UnitUncheckedUpdateWithoutAmenitiesInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutAmenitiesInput, Prisma.UnitUncheckedCreateWithoutAmenitiesInput>
  where?: Prisma.UnitWhereInput
}

export type UnitUpdateToOneWithWhereWithoutAmenitiesInput = {
  where?: Prisma.UnitWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutAmenitiesInput, Prisma.UnitUncheckedUpdateWithoutAmenitiesInput>
}

export type UnitUpdateWithoutAmenitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutUnitsNestedInput
  tenancies?: Prisma.TenancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutAmenitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenancies?: Prisma.TenancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateWithoutTenanciesInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutUnitsInput
  amenities?: Prisma.UnitAmenityCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutTenanciesInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  propertyId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  amenities?: Prisma.UnitAmenityUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutTenanciesInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutTenanciesInput, Prisma.UnitUncheckedCreateWithoutTenanciesInput>
}

export type UnitUpsertWithoutTenanciesInput = {
  update: Prisma.XOR<Prisma.UnitUpdateWithoutTenanciesInput, Prisma.UnitUncheckedUpdateWithoutTenanciesInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutTenanciesInput, Prisma.UnitUncheckedCreateWithoutTenanciesInput>
  where?: Prisma.UnitWhereInput
}

export type UnitUpdateToOneWithWhereWithoutTenanciesInput = {
  where?: Prisma.UnitWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutTenanciesInput, Prisma.UnitUncheckedUpdateWithoutTenanciesInput>
}

export type UnitUpdateWithoutTenanciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutUnitsNestedInput
  amenities?: Prisma.UnitAmenityUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutTenanciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amenities?: Prisma.UnitAmenityUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateManyPropertyInput = {
  id?: string
  title: string
  description?: string | null
  locationInProperty?: string | null
  rentAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: number
  bathrooms?: number
  squareMeters?: number | null
  images?: Prisma.UnitCreateimagesInput | string[]
  status?: $Enums.UnitStatus
  isListed?: boolean
  listingTitle?: string | null
  listingDescription?: string | null
  listedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenancies?: Prisma.TenancyUpdateManyWithoutUnitNestedInput
  amenities?: Prisma.UnitAmenityUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenancies?: Prisma.TenancyUncheckedUpdateManyWithoutUnitNestedInput
  amenities?: Prisma.UnitAmenityUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateManyWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationInProperty?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rentAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  depositAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  squareMeters?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.UnitUpdateimagesInput | string[]
  status?: Prisma.EnumUnitStatusFieldUpdateOperationsInput | $Enums.UnitStatus
  isListed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  listingTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listingDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UnitCountOutputType
 */

export type UnitCountOutputType = {
  tenancies: number
  amenities: number
}

export type UnitCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenancies?: boolean | UnitCountOutputTypeCountTenanciesArgs
  amenities?: boolean | UnitCountOutputTypeCountAmenitiesArgs
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnitCountOutputType
   */
  select?: Prisma.UnitCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeCountTenanciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenancyWhereInput
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeCountAmenitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitAmenityWhereInput
}


export type UnitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  locationInProperty?: boolean
  rentAmount?: boolean
  depositAmount?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  squareMeters?: boolean
  images?: boolean
  status?: boolean
  isListed?: boolean
  listingTitle?: boolean
  listingDescription?: boolean
  listedAt?: boolean
  propertyId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenancies?: boolean | Prisma.Unit$tenanciesArgs<ExtArgs>
  amenities?: boolean | Prisma.Unit$amenitiesArgs<ExtArgs>
  _count?: boolean | Prisma.UnitCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  locationInProperty?: boolean
  rentAmount?: boolean
  depositAmount?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  squareMeters?: boolean
  images?: boolean
  status?: boolean
  isListed?: boolean
  listingTitle?: boolean
  listingDescription?: boolean
  listedAt?: boolean
  propertyId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  locationInProperty?: boolean
  rentAmount?: boolean
  depositAmount?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  squareMeters?: boolean
  images?: boolean
  status?: boolean
  isListed?: boolean
  listingTitle?: boolean
  listingDescription?: boolean
  listedAt?: boolean
  propertyId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  locationInProperty?: boolean
  rentAmount?: boolean
  depositAmount?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  squareMeters?: boolean
  images?: boolean
  status?: boolean
  isListed?: boolean
  listingTitle?: boolean
  listingDescription?: boolean
  listedAt?: boolean
  propertyId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UnitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "locationInProperty" | "rentAmount" | "depositAmount" | "bedrooms" | "bathrooms" | "squareMeters" | "images" | "status" | "isListed" | "listingTitle" | "listingDescription" | "listedAt" | "propertyId" | "createdAt" | "updatedAt", ExtArgs["result"]["unit"]>
export type UnitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenancies?: boolean | Prisma.Unit$tenanciesArgs<ExtArgs>
  amenities?: boolean | Prisma.Unit$amenitiesArgs<ExtArgs>
  _count?: boolean | Prisma.UnitCountOutputTypeDefaultArgs<ExtArgs>
}
export type UnitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}
export type UnitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}

export type $UnitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Unit"
  objects: {
    property: Prisma.$PropertyPayload<ExtArgs>
    tenancies: Prisma.$TenancyPayload<ExtArgs>[]
    amenities: Prisma.$UnitAmenityPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    locationInProperty: string | null
    rentAmount: runtime.Decimal
    depositAmount: runtime.Decimal | null
    bedrooms: number
    bathrooms: number
    squareMeters: number | null
    images: string[]
    status: $Enums.UnitStatus
    isListed: boolean
    listingTitle: string | null
    listingDescription: string | null
    listedAt: Date | null
    propertyId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["unit"]>
  composites: {}
}

export type UnitGetPayload<S extends boolean | null | undefined | UnitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnitPayload, S>

export type UnitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnitCountAggregateInputType | true
  }

export interface UnitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Unit'], meta: { name: 'Unit' } }
  /**
   * Find zero or one Unit that matches the filter.
   * @param {UnitFindUniqueArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnitFindUniqueArgs>(args: Prisma.SelectSubset<T, UnitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Unit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnitFindUniqueOrThrowArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Unit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindFirstArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnitFindFirstArgs>(args?: Prisma.SelectSubset<T, UnitFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Unit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindFirstOrThrowArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Units that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Units
   * const units = await prisma.unit.findMany()
   * 
   * // Get first 10 Units
   * const units = await prisma.unit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unitWithIdOnly = await prisma.unit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnitFindManyArgs>(args?: Prisma.SelectSubset<T, UnitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Unit.
   * @param {UnitCreateArgs} args - Arguments to create a Unit.
   * @example
   * // Create one Unit
   * const Unit = await prisma.unit.create({
   *   data: {
   *     // ... data to create a Unit
   *   }
   * })
   * 
   */
  create<T extends UnitCreateArgs>(args: Prisma.SelectSubset<T, UnitCreateArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Units.
   * @param {UnitCreateManyArgs} args - Arguments to create many Units.
   * @example
   * // Create many Units
   * const unit = await prisma.unit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnitCreateManyArgs>(args?: Prisma.SelectSubset<T, UnitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Units and returns the data saved in the database.
   * @param {UnitCreateManyAndReturnArgs} args - Arguments to create many Units.
   * @example
   * // Create many Units
   * const unit = await prisma.unit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Units and only return the `id`
   * const unitWithIdOnly = await prisma.unit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Unit.
   * @param {UnitDeleteArgs} args - Arguments to delete one Unit.
   * @example
   * // Delete one Unit
   * const Unit = await prisma.unit.delete({
   *   where: {
   *     // ... filter to delete one Unit
   *   }
   * })
   * 
   */
  delete<T extends UnitDeleteArgs>(args: Prisma.SelectSubset<T, UnitDeleteArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Unit.
   * @param {UnitUpdateArgs} args - Arguments to update one Unit.
   * @example
   * // Update one Unit
   * const unit = await prisma.unit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnitUpdateArgs>(args: Prisma.SelectSubset<T, UnitUpdateArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Units.
   * @param {UnitDeleteManyArgs} args - Arguments to filter Units to delete.
   * @example
   * // Delete a few Units
   * const { count } = await prisma.unit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnitDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Units.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Units
   * const unit = await prisma.unit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnitUpdateManyArgs>(args: Prisma.SelectSubset<T, UnitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Units and returns the data updated in the database.
   * @param {UnitUpdateManyAndReturnArgs} args - Arguments to update many Units.
   * @example
   * // Update many Units
   * const unit = await prisma.unit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Units and only return the `id`
   * const unitWithIdOnly = await prisma.unit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Unit.
   * @param {UnitUpsertArgs} args - Arguments to update or create a Unit.
   * @example
   * // Update or create a Unit
   * const unit = await prisma.unit.upsert({
   *   create: {
   *     // ... data to create a Unit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Unit we want to update
   *   }
   * })
   */
  upsert<T extends UnitUpsertArgs>(args: Prisma.SelectSubset<T, UnitUpsertArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Units.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitCountArgs} args - Arguments to filter Units to count.
   * @example
   * // Count the number of Units
   * const count = await prisma.unit.count({
   *   where: {
   *     // ... the filter for the Units we want to count
   *   }
   * })
  **/
  count<T extends UnitCountArgs>(
    args?: Prisma.Subset<T, UnitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Unit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnitAggregateArgs>(args: Prisma.Subset<T, UnitAggregateArgs>): Prisma.PrismaPromise<GetUnitAggregateType<T>>

  /**
   * Group by Unit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnitGroupByArgs['orderBy'] }
      : { orderBy?: UnitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Unit model
 */
readonly fields: UnitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Unit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tenancies<T extends Prisma.Unit$tenanciesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$tenanciesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenancyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  amenities<T extends Prisma.Unit$amenitiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$amenitiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitAmenityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Unit model
 */
export interface UnitFieldRefs {
  readonly id: Prisma.FieldRef<"Unit", 'String'>
  readonly title: Prisma.FieldRef<"Unit", 'String'>
  readonly description: Prisma.FieldRef<"Unit", 'String'>
  readonly locationInProperty: Prisma.FieldRef<"Unit", 'String'>
  readonly rentAmount: Prisma.FieldRef<"Unit", 'Decimal'>
  readonly depositAmount: Prisma.FieldRef<"Unit", 'Decimal'>
  readonly bedrooms: Prisma.FieldRef<"Unit", 'Int'>
  readonly bathrooms: Prisma.FieldRef<"Unit", 'Int'>
  readonly squareMeters: Prisma.FieldRef<"Unit", 'Float'>
  readonly images: Prisma.FieldRef<"Unit", 'String[]'>
  readonly status: Prisma.FieldRef<"Unit", 'UnitStatus'>
  readonly isListed: Prisma.FieldRef<"Unit", 'Boolean'>
  readonly listingTitle: Prisma.FieldRef<"Unit", 'String'>
  readonly listingDescription: Prisma.FieldRef<"Unit", 'String'>
  readonly listedAt: Prisma.FieldRef<"Unit", 'DateTime'>
  readonly propertyId: Prisma.FieldRef<"Unit", 'String'>
  readonly createdAt: Prisma.FieldRef<"Unit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Unit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Unit findUnique
 */
export type UnitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit findUniqueOrThrow
 */
export type UnitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit findFirst
 */
export type UnitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Units.
   */
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit findFirstOrThrow
 */
export type UnitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Units.
   */
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit findMany
 */
export type UnitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Units to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit create
 */
export type UnitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The data needed to create a Unit.
   */
  data: Prisma.XOR<Prisma.UnitCreateInput, Prisma.UnitUncheckedCreateInput>
}

/**
 * Unit createMany
 */
export type UnitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Units.
   */
  data: Prisma.UnitCreateManyInput | Prisma.UnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Unit createManyAndReturn
 */
export type UnitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * The data used to create many Units.
   */
  data: Prisma.UnitCreateManyInput | Prisma.UnitCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Unit update
 */
export type UnitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The data needed to update a Unit.
   */
  data: Prisma.XOR<Prisma.UnitUpdateInput, Prisma.UnitUncheckedUpdateInput>
  /**
   * Choose, which Unit to update.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit updateMany
 */
export type UnitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Units.
   */
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyInput>
  /**
   * Filter which Units to update
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to update.
   */
  limit?: number
}

/**
 * Unit updateManyAndReturn
 */
export type UnitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * The data used to update Units.
   */
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyInput>
  /**
   * Filter which Units to update
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Unit upsert
 */
export type UnitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The filter to search for the Unit to update in case it exists.
   */
  where: Prisma.UnitWhereUniqueInput
  /**
   * In case the Unit found by the `where` argument doesn't exist, create a new Unit with this data.
   */
  create: Prisma.XOR<Prisma.UnitCreateInput, Prisma.UnitUncheckedCreateInput>
  /**
   * In case the Unit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnitUpdateInput, Prisma.UnitUncheckedUpdateInput>
}

/**
 * Unit delete
 */
export type UnitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter which Unit to delete.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit deleteMany
 */
export type UnitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Units to delete
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to delete.
   */
  limit?: number
}

/**
 * Unit.tenancies
 */
export type Unit$tenanciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenancy
   */
  select?: Prisma.TenancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenancy
   */
  omit?: Prisma.TenancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenancyInclude<ExtArgs> | null
  where?: Prisma.TenancyWhereInput
  orderBy?: Prisma.TenancyOrderByWithRelationInput | Prisma.TenancyOrderByWithRelationInput[]
  cursor?: Prisma.TenancyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TenancyScalarFieldEnum | Prisma.TenancyScalarFieldEnum[]
}

/**
 * Unit.amenities
 */
export type Unit$amenitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnitAmenity
   */
  select?: Prisma.UnitAmenitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnitAmenity
   */
  omit?: Prisma.UnitAmenityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitAmenityInclude<ExtArgs> | null
  where?: Prisma.UnitAmenityWhereInput
  orderBy?: Prisma.UnitAmenityOrderByWithRelationInput | Prisma.UnitAmenityOrderByWithRelationInput[]
  cursor?: Prisma.UnitAmenityWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UnitAmenityScalarFieldEnum | Prisma.UnitAmenityScalarFieldEnum[]
}

/**
 * Unit without action
 */
export type UnitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
}
